import{addLog}from"./clinical-engine.js";
import{buildSequence,currentPhase,advancePhase,injectScenarioError,injectScenarioTrick,sessionSnapshot}from"./algorithms.js";
import{setupRemoteControl}from"./remote-control.js";
const $=id=>document.getElementById(id);
function injectUi(){
  if(!$("remoteSessionBtn")){const btn=document.createElement("button");btn.id="remoteSessionBtn";btn.className="btn";btn.type="button";btn.textContent="Instructor remoto";const voice=$("voiceBtn");voice?.parentElement?.insertBefore(btn,voice)}
  if(!$("facilitatorBar")){const bar=document.createElement("div");bar.id="facilitatorBar";bar.className="facilitator-bar hidden";bar.innerHTML='<span><b>Control instructor</b> · fase <span id="quickPhaseCount">1/1</span></span><div><button id="quickAdvanceBtn" class="btn primary" type="button">Avanzar fase</button><button id="quickErrorBtn" class="btn danger" type="button">Error crítico</button><button id="quickTrickBtn" class="btn warning" type="button">Evento / truco</button></div>';const grid=document.querySelector("#simView .simgrid");grid?.parentElement?.insertBefore(bar,grid)}
  if(!$("algorithmCard")){const patient=document.querySelector("#simView .simgrid > aside.panel.form");const card=document.createElement("div");card.id="algorithmCard";card.className="algorithm-card";card.innerHTML='<div class="heading"><span class="eyebrow">SECUENCIA ACTUAL</span><span id="phaseCount" class="chip">1/1</span></div><h3 id="phaseTitle">Valoración inicial</h3><p id="phaseInstruction"></p><div id="phasePrompt" class="algorithm-prompt"></div>';patient?.insertBefore(card,$("goalCount")?.parentElement||null)}
  const controls=$("instructorControls");
  if(controls&&!$("remoteControlBox")){const box=document.createElement("section");box.id="remoteControlBox";box.className="remote-box";box.innerHTML='<div class="heading"><div><p class="eyebrow">DOS DISPOSITIVOS</p><h3>Conexión remota</h3></div><span id="remoteStatus" class="chip">Sin conectar</span></div><p class="muted">En el dispositivo del monitor crea la sesión. En el segundo dispositivo abre la misma página, entra al panel e introduce el código.</p><div class="grid2"><button id="createRemoteRoomBtn" type="button" class="btn primary">Crear sesión en monitor</button><div class="remote-code"><small>Código</small><b id="remoteRoomCode">—</b></div></div><label>Conectar este dispositivo como instructor<input id="remoteRoomInput" placeholder="Ej. SIM-AB12CD"></label><p><button id="connectRemoteBtn" type="button" class="btn">Conectar</button> <button id="copyRemoteLinkBtn" type="button" class="btn">Copiar enlace</button></p>';controls.prepend(box);const seq=document.createElement("section");seq.className="instructor-sequence";seq.innerHTML='<div class="heading"><div><p class="eyebrow">SECUENCIA DEL CASO</p><h3 id="instructorPhaseTitle">Sin escenario activo</h3></div><span id="instructorPhaseCount" class="chip">0/0</span></div><p id="instructorPhaseInstruction" class="muted"></p><p><button id="advancePhaseBtn" type="button" class="btn primary">Avanzar fase</button> <button id="scenarioErrorBtn" type="button" class="btn danger">Error crítico</button> <button id="scenarioTrickBtn" type="button" class="btn warning">Evento / truco</button></p>';box.after(seq)}
}
export function setupAdvancedControl(api){
  injectUi();let lastSession=null;
  function ensureSequence(s){if(!s)return;if(!s.sequence||!s.sequence.length){s.sequence=buildSequence(s.scenario,s.meta?.program);s.phaseIndex=0;s.trickIndex=0;addLog(s,`SECUENCIA INICIADA: ${currentPhase(s)?.title||"Valoración"}`,"phase")}}
  function renderPhase(snapshot=null){const s=api.getSession();if(s)ensureSequence(s);const p=s?currentPhase(s):snapshot?.phase,index=s?(s.phaseIndex||0):(snapshot?.phaseIndex||0),count=s?(s.sequence?.length||0):(snapshot?.phaseCount||0);if($("phaseTitle"))$("phaseTitle").textContent=p?.title||"Sin fase";if($("phaseInstruction"))$("phaseInstruction").textContent=p?.instruction||"";if($("phasePrompt"))$("phasePrompt").textContent=p?.prompt||"";if($("phaseCount"))$("phaseCount").textContent=count?`${index+1}/${count}`:"0/0";if($("quickPhaseCount"))$("quickPhaseCount").textContent=count?`${index+1}/${count}`:"0/0";if($("instructorPhaseTitle"))$("instructorPhaseTitle").textContent=p?.title||"Sin escenario activo";if($("instructorPhaseInstruction"))$("instructorPhaseInstruction").textContent=p?.instruction||"";if($("instructorPhaseCount"))$("instructorPhaseCount").textContent=count?`${index+1}/${count}`:"0/0"}
  function populateRemote(snapshot){const v=snapshot?.vitals||{};[["manualHr","hr"],["manualSpo2","spo2"],["manualSys","sys"],["manualDia","dia"],["manualRr","rr"],["manualEtco2","etco2"]].forEach(([id,k])=>{if($(id))$(id).value=v[k]??0});if($("rhythmSelect"))$("rhythmSelect").value=v.rhythm||"Sinusal";if($("decisionSelect"))$("decisionSelect").value=snapshot?.instructorDecision||"";renderPhase(snapshot);if($("toggleDeteriorationBtn"))$("toggleDeteriorationBtn").textContent=snapshot?.deterioration?"Detener deterioro":"Iniciar deterioro"}
  function renderAndSend(){api.render();renderPhase();const s=api.getSession();if(s)remote.sendSnapshot(sessionSnapshot(s))}
  function setRhythm(s,rhythm){s.vitals.rhythm=rhythm;if(["Asistolia","FV"].includes(rhythm))Object.assign(s.vitals,{hr:0,sys:0,dia:0});else if(rhythm==="AESP")Object.assign(s.vitals,{hr:70,sys:0,dia:0});else if(rhythm==="TSV")s.vitals.hr=220;else if(rhythm==="TV")s.vitals.hr=190;else if(rhythm==="Bradicardia")s.vitals.hr=50;else if(rhythm==="Sinusal"&&s.vitals.hr<60)s.vitals.hr=110}
  function command(name,payload={}){if(remote.isRemoteInstructor())return remote.sendCommand(name,payload)||api.toast("El instructor remoto no está conectado.");const s=api.getSession();if(!s)return api.toast("No hay un escenario activo en el monitor.");ensureSequence(s);if(name==="setVitals"){Object.assign(s.vitals,payload);addLog(s,"Instructor modificó FC, SpO₂, TA, FR y ETCO₂","instructor")}if(name==="setRhythm"){setRhythm(s,payload.rhythm);addLog(s,`Ritmo activado: ${payload.rhythm}`,"instructor")}if(name==="toggleDeterioration"){s.deterioration=!s.deterioration;addLog(s,s.deterioration?"Deterioro iniciado":"Deterioro detenido","instructor")}if(name==="manualCriticalError"){s.criticalErrors++;addLog(s,`ERROR CRÍTICO: ${payload.message}`,"critical")}if(name==="setDecision"){s.instructorDecision=payload.decision||"";addLog(s,`Decisión del instructor: ${payload.decision||"Automática"}`,"instructor")}if(name==="advancePhase"){const p=advancePhase(s);addLog(s,`FASE AVANZADA: ${p?.title||"fase final"}`,"phase");api.toast(p?.title||"Fase final")}if(name==="scenarioError"){const m=injectScenarioError(s);addLog(s,`ERROR / EVOLUCIÓN DESFAVORABLE: ${m}`,"critical");api.toast("Se activó deterioro por error")}if(name==="scenarioTrick"){const e=injectScenarioTrick(s);addLog(s,`EVENTO SORPRESA: ${e}`,"trick");api.toast("Evento sorpresa activado")}if(name==="finish"){api.finish();return}renderAndSend()}
  const remote=setupRemoteControl({onCommand:(name,payload)=>command(name,payload),onSnapshot:populateRemote,onRequestSnapshot:renderAndSend,onNotice:api.toast,onStatus:(text,state)=>{if($("connectionBadge"))$("connectionBadge").textContent=state==="connected"?"Remoto conectado":text.includes("Esperando")?"Esperando instructor":"Local";if(state==="connected"&&api.getSession())api.toast("Instructor remoto conectado")},onRoom:id=>{api.toast(`Código remoto: ${id}`);renderAndSend()}});
  $("remoteSessionBtn").onclick=()=>$("instructorBtn").click();$("createRemoteRoomBtn").onclick=()=>api.getSession()?remote.createMonitorRoom():api.toast("Inicia primero un escenario en el monitor.");$("connectRemoteBtn").onclick=()=>remote.connectInstructor($("remoteRoomInput").value);$("copyRemoteLinkBtn").onclick=async()=>api.toast(await remote.copyInstructorLink()?"Enlace copiado":"Primero crea una sesión remota");
  $("advancePhaseBtn").onclick=()=>command("advancePhase");$("scenarioErrorBtn").onclick=()=>command("scenarioError");$("scenarioTrickBtn").onclick=()=>command("scenarioTrick");$("quickAdvanceBtn").onclick=()=>command("advancePhase");$("quickErrorBtn").onclick=()=>command("scenarioError");$("quickTrickBtn").onclick=()=>command("scenarioTrick");
  const localApply=$("applyVitalsBtn").onclick;$("applyVitalsBtn").onclick=()=>remote.isRemoteInstructor()?command("setVitals",{hr:+$("manualHr").value,spo2:+$("manualSpo2").value,sys:+$("manualSys").value,dia:+$("manualDia").value,rr:+$("manualRr").value,etco2:+$("manualEtco2").value,rhythm:$("rhythmSelect").value}):localApply?.();
  const localRhythm=$("rhythmSelect").onchange;$("rhythmSelect").onchange=e=>remote.isRemoteInstructor()?command("setRhythm",{rhythm:e.target.value}):localRhythm?.call($("rhythmSelect"),e);
  const localDeterioration=$("toggleDeteriorationBtn").onclick;$("toggleDeteriorationBtn").onclick=e=>remote.isRemoteInstructor()?command("toggleDeterioration"):localDeterioration?.call(e.currentTarget,e);
  const localDecision=$("decisionSelect").onchange;$("decisionSelect").onchange=e=>remote.isRemoteInstructor()?command("setDecision",{decision:e.target.value}):localDecision?.call($("decisionSelect"),e);
  const localFinish=$("instructorFinishBtn").onclick;$("instructorFinishBtn").onclick=e=>remote.isRemoteInstructor()?command("finish"):localFinish?.call(e.currentTarget,e);
  $("unlockBtn").addEventListener("click",()=>setTimeout(()=>{if(!$("instructorControls").classList.contains("hidden")&&api.getSession())$("facilitatorBar").classList.remove("hidden")},80));
  setInterval(()=>{const s=api.getSession();if(s!==lastSession){lastSession=s;if(s){ensureSequence(s);renderAndSend()}}else if(s){renderPhase();remote.sendSnapshot(sessionSnapshot(s))}},1000);
  if(remote.instructorMode)setTimeout(()=>{$("instructorBtn").click();api.toast("Introduce el PIN y conecta con el código de la sesión.")},350);
  return{command,renderPhase,populateRemote}
}
